theme = 'PaperMod'
baseURL = 'https://huangyiyang0812.github.io/huangyiyang/'
languageCode = 'zh-cn'
title = 'Yiyang的个人网页'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true





